[workspace]
members = [
    "fmo_api_types",
    "fmo_frontend",
    "fmo_server",
]

resolver = "2"

[workspace.dependencies]
fedimint-api-client = { version = "0.7" } # TODO: apply XYZ patch
fedimint-core = { version = "0.7" }
fedimint-ln-common = { version = "0.7" }
fedimint-mint-common = { version = "0.7" }
fedimint-wallet-common = { version = "0.7" }
