[package]
name = "fedimint-observer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fedimint-core = "0.3.0-rc.3"

axum = { version = "0.7.5", features = ["json"] }
serde = { version = "1.0.197", features = ["derive"] }
tokio = { version = "1.37.0", features = ["full"]}
anyhow = "1.0.81"
